### ISSUE TITLE
Stack trace when starting Node without Network Connectivity

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico-docker#430]
If calico/node docker images is not available locally, calico-docker will attempt to pull it. But without a network connection to dockerhub, it will dump a stack trace and quit. We should catch this exception and tell the user that they're missing the calico/node local image, and unable to pull from dockerhub.
```
~/Metaswitch/calico-docker(master ✔) sudo calicoctl node --ip=192.168.1.1
Pulling Docker image calico/node:latest
Unexpected error executing command.

Traceback (most recent call last):
  File "<string>", line 89, in <module>
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.node", line 164, in node
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.node", line 290, in node_start
  File "/code/build/calicoctl/out00-PYZ.pyz/docker.client", line 484, in create_container
  File "/code/build/calicoctl/out00-PYZ.pyz/docker.client", line 492, in create_container_from_config
  File "/code/build/calicoctl/out00-PYZ.pyz/docker.client", line 126, in _result
  File "/code/build/calicoctl/out00-PYZ.pyz/docker.client", line 122, in _raise_for_status
APIError: 404 Client Error: Not Found ("No such image: calico/node:latest (tag: latest)")
```

**Comment by robbrockbank** [comment]
Fixed by #440
