### ISSUE TITLE
ip6_tables not installed in vagrant demo

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-docker#553]
Seen in the CoreOS `vagrant up` demo in the Felix logs.

```
ip6tables-save v1.4.21: Cannot initialize: iptables who? (do you need to insmod?)

2015-10-21 20:46:27,444 [ERROR][7354/6] calico.felix.actor 233: Exception processing 7f95d8c99f7a (_load_chain_names_from_iptables)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/calico/felix/actor.py", line 231, in _step
    result = msg.method()
  File "/usr/local/lib/python2.7/dist-packages/calico/felix/fiptables.py", line 187, in _load_chain_names_from_iptables
    self.table])
  File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 167, in check_output
    raise ex
CalledProcessError: Command '['ip6tables-save', '--table', 'filter']' returned non-zero exit status 1
```

Looks like `ip6_tables` is not installed anymore after the `checksystem --fix` changes.

**Comment by caseydavenport** [comment]
Looks like an issue with the way we're calling `modprobe` in `node_start(..)`

We run the following:
```
modprobe xt_set ip6_tables
```

Which appears to install `xt_set`, but not `ip6_tables`.  I think we need to include the `-a` option on modprobe, which indicates that it should treat all arguments as modules to be installed.

e.g
```
modprobe -a xt_set ip6_tables
```

**Comment by tomdee** [comment]
D'oh. Thanks for investigating.
