### ISSUE TITLE
Uncaught exception when passing nonexistant IF to `calicoctl container ip add` command

### ISSUE THREAD

**Issue by TrimBiggs** [projectcalico/calico-docker#565]
```
$ calicoctl container test2 ip add ipv4 --interface=bad_if
CalledProcessError: Command '['ip', 'netns', 'exec', '244c2a2079d511e5bd1a080027f532f6', 'ip', '-4', 'addr', 'add', '192.168.0.7/32', 'dev', 'bad_if']' returned non-zero exit status 1

Traceback (most recent call last):
  File "<string>", line 104, in <module>
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.container", line 121, in container
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.container", line 414, in container_ip_add
  File "/code/build/calicoctl/out00-PYZ.pyz/pycalico.netns", line 192, in add_ip_to_ns_veth
  File "/code/build/calicoctl/out00-PYZ.pyz/pycalico.netns", line 267, in check_output
  File "/code/build/calicoctl/out00-PYZ.pyz/subprocess32", line 635, in check_output
CalledProcessError: Command '['ip', 'netns', 'exec', '244c2a2079d511e5bd1a080027f532f6', 'ip', '-4', 'addr', 'add', '192.168.0.7/32', 'dev', 'bad_if']' returned non-zero exit status 1
```

**Comment by TrimBiggs** [comment]
Fixed by #578
