### ISSUE TITLE
Stacktrace during Ctrl-C

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico-docker#602]
```
$ sudo calico_containers/calicoctl.py node 
No IP provided. Using detected IP: 172.17.8.10
Pulling Docker image calico/node:latest

^CKeyboardInterrupt: 

Traceback (most recent call last):
  File "calico_containers/calicoctl.py", line 104, in <module>
    getattr(command_module, command)(arguments)
  File "/home/gulfstream/calico-docker/calico_containers/calico_ctl/node.py", line 209, in node
    libnetwork_image=libnetwork_image)
  File "/home/gulfstream/calico-docker/calico_containers/calico_ctl/node.py", line 313, in node_start
    _start_node_container(ip, ip6, etcd_authority, log_dir, node_image, detach)
  File "/home/gulfstream/calico-docker/calico_containers/calico_ctl/node.py", line 363, in _start_node_container
    _find_or_pull_node_image(node_image)
  File "/home/gulfstream/calico-docker/calico_containers/calico_ctl/node.py", line 595, in _find_or_pull_node_image
    docker_client.pull(image_name)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 909, in pull
    headers=headers, stream=stream, timeout=None)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 103, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 610, in send
    r.content
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 730, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 655, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 587, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 629, in _read_chunked
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
```

**Comment by TrimBiggs** [comment]
This isn't quite as simple as I thought.  I was unable to catch the KeyboardInterrupt exception within the calicoctl and node commands.  It may be a matter of catching a SIGINT with a signal handler.
